services:
  - type: web
    name: datatrackpro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This means you'll set it manually in the Render dashboard